# Generated by Django 4.2.20 on 2025-04-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
